[package]
name = "integration_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cashu-rs = { path = ".." }
url = "2.3.1"
tokio = { version = "1.27.0", features = ["full"] }