[package]
name = "cdk-phoenixd"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.63.0" # MSRV
description = "CDK ln backend for phoenixd"

[dependencies]
async-trait = "0.1"
anyhow = "1"
axum = "0.6.20"
bitcoin = { version = "0.32.2", default-features = false }
cdk = { path = "../cdk", default-features = false, features = ["mint"] }
futures = { version = "0.3.28", default-features = false }
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["attributes", "log"] }
thiserror = "1"
phoenixd-rs = "0.3.0"
uuid = { version = "1", features = ["v4"] }
