[package]
name = "cdk-fake-wallet"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.63.0" # MSRV
description = "CDK fake ln backend"

[dependencies]
async-trait = "0.1.74"
bitcoin = { version = "0.32.2", default-features = false }
cdk = { path = "../cdk", default-features = false, features = ["mint"] }
futures = { version = "0.3.28", default-features = false }
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["attributes", "log"] }
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
lightning-invoice = { version = "0.32.0", features = ["serde", "std"] }
lightning = "0.0.124"
tokio-stream = "0.1.15"
rand = "0.8.5"
