[package]
name = "cdk-axum"
version = "0.5.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.63.0"                            # MSRV
description = "Cashu CDK axum webserver"

[dependencies]
anyhow = "1"
async-trait = "0.1.83"
axum = { version = "0.6.20", features = ["ws"] }
cdk = { path = "../cdk", version = "0.5.0", default-features = false, features = [
    "mint",
] }
tokio = { version = "1", default-features = false, features = ["io-util"] }
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
    "log",
] }
utoipa = { version = "4", features = [
    "preserve_order",
    "preserve_path_order",
], optional = true }
futures = { version = "0.3.28", default-features = false }
moka = { version = "0.11.1", features = ["future"] }
serde_json = "1"
paste = "1.0.15"
serde = { version = "1.0.210", features = ["derive"] }

[features]
swagger = ["cdk/swagger", "dep:utoipa"]
