[package]
name = "cdk-axum"
version = "0.1.0"
edition = "2021"
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Cashu CDK axum webserver"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
cdk = { workspace = true, default-features = false, features = ["mint"] }
tokio.workspace = true
tower-http = { version = "0.5.2", features = ["cors"] }
tracing.workspace = true
futures.workspace = true
