[package]
name = "cdk-axum"
version = "0.3.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.63.0" # MSRV
description = "Cashu CDK axum webserver"

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.6.20"
cdk = { path = "../cdk", default-features = false, features = ["mint"] }
tokio = { version = "1", default-features = false }
tower-http = { version = "0.4.4", features = ["cors"] }
tracing = { version = "0.1", default-features = false, features = ["attributes", "log"] }
futures = { version = "0.3.28", default-features = false }
