[package]
name = "cdk-rexie"
version = "0.1.0"
edition = "2021"
authors = ["CDK Developers"]
description = "Indexdb storage backend for CDK in the browser"
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["wallet"]
wallet = ["cdk/wallet"]

[dependencies]
rexie = "0.5.0"
cdk = { workspace = true, default-features = false }
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
serde-wasm-bindgen.workspace = true
web-sys.workspace = true
