[package]
name = "cdk-rexie"
version = "0.7.1"
edition = "2021"
authors = ["CDK Developers"]
description = "Indexdb storage backend for CDK in the browser"
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.75.0" # MSRV

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["wallet"]
wallet = ["cdk/wallet"]

[dependencies]
rexie = "0.6.0"
cdk = { path = "../cdk", version = "0.7.2", default-features = false }
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
serde-wasm-bindgen = "0.6.5"
web-sys =  { version = "0.3.69", default-features = false, features = ["console"] }
