[bindings.kotlin]
package_name = "org.cashudevkit"
cdylib_name = "cdk_ffi"

[bindings.python]
cdylib_name = "cdk_ffi"

[bindings.swift]
module_name = "CashuDevKit"
cdylib_name = "cdk_ffi"
generate_codable_conformance = true
generate_immutable_records = true
