[package]
name = "cdk-lnd"
version = "0.7.1"
edition = "2021"
authors = ["CDK Developers"]
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
description = "CDK ln backend for lnd"

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
cdk = { path = "../cdk", version = "0.7.2", default-features = false, features = ["mint"] }
fedimint-tonic-lnd = "0.2.0"
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
