[package]
name = "ln-regtest-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0" # MSRV


[dependencies]
anyhow = "1"
async-trait = "0.1"
bitcoincore-rpc = "0.19.0"
cln-rpc = "0.4.0"
fedimint-tonic-lnd = "0.2.0"
lightning = "0.1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3.12.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
