[package]
name = "cdk-mint-rpc"
version = "0.7.1"
edition = "2021"
authors = ["CDK Developers"]
description = "CDK mintd mint managment RPC client and server"
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.75.0"                            # MSRV

[[bin]]
name = "cdk-mint-cli"
path = "src/bin/mint_rpc_cli.rs"

[dependencies]
anyhow.workspace = true
cdk = { workspace = true, features = [
    "mint",
] }
clap.workspace = true
tonic = { version = "0.9", features = [
    "channel",
    "tls",
    "tls-webpki-roots",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
prost = "0.11.0"
home = "0.5.5"


[build-dependencies]
tonic-build = "0.9"
